### ISSUE TITLE
Incorrect duplicate rows count

### ISSUE THREAD

**Issue by SergioG-M** [ydataai/pandas-profiling#1012]
### Current Behaviour

The duplicated rows count is different between pandas and pandas-profiling when there are nan's in columns

### Expected Behaviour

The count should be equal

### Data Description

I attach a simple example

![image](https://user-images.githubusercontent.com/61322372/180415055-83fc2fec-fc2a-4921-acf9-0a9a38ccb645.png)

### Code that reproduces the bug

```Python
import pandas as pd
import numpy as np

df = pd.DataFrame({"a": [np.nan, np.nan, 2], "b": [1, 1, 3]})
sum(df.duplicated())

from pandas_profiling import ProfileReport

profile = ProfileReport(df, title="Pandas Profiling Report")
```

### pandas-profiling version

3.2.0

### Dependencies

```Text
numpy==1.22.4
pandas==1.3.3
```

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by SergioG-M** [comment]
Any update on this?

**Comment by fabclmnt** [comment]
@SergioG-M is included for the next release. But still under development.

**Comment by shawn-eary** [comment]
Probably unrelated to this particular bug, but I just took a table of X number rows and then inserted a copy of the table onto itself. The table then had X*2 rows. after the insert operation there should have been **at least** X number of duplicate rows.  Unfortunately, ydata_profiles returned a number of duplicate rows that was far less than the minimal expected X number of rows.

In contrast, this method https://scales.arabpsychology.com/stats/how-to-find-duplicates-in-pyspark-dataframe/ returned the duplicate rows count that I would expect.

I think this package maybe still has a bug in detecting duplicate number of rows.

**Comment by shawn-eary** [comment]
> Probably unrelated to this particular bug, but I just took a table of X number rows and then inserted a copy of the table onto itself. The table then had X*2 rows. After the insert operation, there should have been **at least** X number of duplicate rows. Unfortunately, ydata_profiling returned a number of duplicate rows that was far less than the minimal expected X number of duplicate rows.
> 
> In contrast, this method https://scales.arabpsychology.com/stats/how-to-find-duplicates-in-pyspark-dataframe/ returned the duplicate rows count that I would expect.
> 
> I think the ydata_profiling package maybe still has a bug in detecting duplicate number of rows.

I'm not sure what version of ydata_profiling I'm using but the differences I found in detecting duplicate rows among different tools were in how a duplicate was defined. It looks like my current version of ydata_profiling only counts a duplicate once no matter how many times it is duplicated, while the method at https://scales.arabpsychology.com/stats/how-to-find-duplicates-in-pyspark-dataframe/ counts a duplicate each time it occurs.

**Given the data set:**
1, 2, 3
4, 5, 6
1, 2, 3
1, 2, 3

**It appears that:**
ydata_profiling will return duplicates = 1
while the Arab Psychology link mentioned above with return duplicates =3

**Comment by piotrp88** [comment]
> > Probably unrelated to this particular bug, but I just took a table of X number rows and then inserted a copy of the table onto itself. The table then had X*2 rows. After the insert operation, there should have been **at least** X number of duplicate rows. Unfortunately, ydata_profiling returned a number of duplicate rows that was far less than the minimal expected X number of duplicate rows.
> > In contrast, this method https://scales.arabpsychology.com/stats/how-to-find-duplicates-in-pyspark-dataframe/ returned the duplicate rows count that I would expect.
> > I think the ydata_profiling package maybe still has a bug in detecting duplicate number of rows.
> 
> I'm not sure what version of ydata_profiling I'm using but the differences I found in detecting duplicate rows among different tools were in how a duplicate was defined. It looks like my current version of ydata_profiling only counts a duplicate once no matter how many times it is duplicated, while the method at https://scales.arabpsychology.com/stats/how-to-find-duplicates-in-pyspark-dataframe/ counts a duplicate each time it occurs.
> 
> **Given the data set:** 1, 2, 3 4, 5, 6 1, 2, 3 1, 2, 3
> 
> **It appears that:** ydata_profiling will return duplicates = 1 while the Arab Psychology link mentioned above with return duplicates =3

It's exactly as you pointed out. You can verify it also in this way:

```python
# Count all the duplicated rows, including the first one
all_dup = df_NEW.duplicated(keep=False).sum()

# Count all the duplicated rows, except from the first one
not_first_dup = df_NEW.duplicated(keep="first").sum() # keep = 'first' is the default Pandas' behaviour

# Delete the duplicated rows using Pandas
deleted_rows = df_NEW.shape[0] - df_NEW.drop_duplicates().shape[0]
```

You will observe that `all_dup - deleted_rows ` equals the duplicated count provided by ydata-profiling.
