### ISSUE TITLE
Fail to allocate bitmap error when generating separate HTML reports in sequence (not concurrently)

### ISSUE THREAD

**Issue by duncanrjones** [ydataai/pandas-profiling#1017]
Hi,

I'm using pandas-profiling to do null checks and summarize distribution in columns in a postgresql database. I can run the script separately for each table with no issue, but if I try to do a for loop with the tables I get a "fail to allocate bitmap" error. If I export to JSON, it is no issue.

I couldn't find a relevant post about this in this issues forum but I saw it mentioned here: https://stackoverflow.com/questions/67327510/fail-to-allocate-bitmap-error-on-numeric-data-using-pandas-profiling/67904007#67904007

As well as in a variety of posts about matplotlib, all of which seem to settle on using plt.close() as a fix. I looked at the visualization folder in the pandas-profiling library and was wondering if this could potentially be included somewhere.

### Current Behavior

When I attempt to profile two data frames sequentially in the same script, the second export to HTML fails with the following message:

> Summarize dataset: 100%|██████████| 246/246 [00:00<00:00, 384.36it/s, Completed]
> Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]Fail to allocate bitmap

> Process finished with exit code -2147483645

### Expected behavior

I expect the script to produce separate HTML reports for each table in the for loop.

### Data description

Tables in a postgresql database.

### Code the reproduces the bug

Apologies as I cannot provide the equivalent data, but the code is essentially as follows (please note that the reports are generated sequentially and not concurrently):

    for f in nameslist:

        # Establish empty column dictionary

        columndict = {}

        crsr.execute(f'select column_name from information_schema.columns where table_schema = \'{schema}\' and \
        table_name = \'{f}\' ;')
        columns = crsr.fetchall()
        columnslist = [row[0] for row in columns]

        # Column for loop

        for i in columnslist:

            crsr.execute(f'select {i} from {schema}.{f};')

            # Put column data into list, add list to dictionary.

            data = crsr.fetchall()
            datalist = [row[0] for row in data]
            columndict[str(i)] = datalist

        # Convert column data dictionary to data frame and generate profile.

        df = pd.DataFrame.from_dict(columndict)
        profile = ProfileReport(df, dark_mode=True, correlations=None, reject_variables=False, \
                                minimal=True, title=f'{f} Profile Report')
        profile.to_file(f'{profile_output_location}{f}_profile_report{date_time}.html')

#### pandas-profiling version

pandas-profiling==3.2.0

### Dependencies

I'm also using psycopg2 and pandas here

#### OS

Windows 10

**Comment by fabclmnt** [comment]
Hi @duncanrjones thank you for the provided detail. 

This is indeed a bug. We will check the fix that can be done.

**Comment by fabclmnt** [comment]
@duncanrjones after assessing the last release from pandas-profiling, we cannot replicate this issue in different python env (3.7, 2.8, and 3.9) with pandas-profiling=3.2.0.

Can you please confirm whether you are still able to have it replicated with a more up-to-date version of the package? After further assessment, it seems related to your windows python installation and missing dll.

**Comment by duncanrjones** [comment]
Thanks for taking time to look into it @fabclmnt, I will try it on a different server ASAP and let you know.

**Comment by fabclmnt** [comment]
@duncanrjones I'll be closing this one. But happy to re-open in case you're not able to solve it.

**Comment by duncanrjones** [comment]
Thanks so much @fabclmnt, sorry I didn't get back to you yet--still haven't had a chance to try it again. I will definitely update you if there's any issues and I do really appreciate your time.

Thanks again!
