### ISSUE TITLE
Multiple duplicated correlations in "Alerts" section

### ISSUE THREAD

**Issue by soliverc** [ydataai/pandas-profiling#1019]
### Current Behaviour

When the HTML report is generated, I checked the Alerts section and found duplicated correlations.

This bug is even present in Pandas Profiling's official examples on the documentation page, Please follow this link and click the "Alerts" tab. You will see the correlation between Pclass and Fare flagged at least 6 times. 

 https://pandas-profiling.ydata.ai/examples/master/titanic/titanic_report.html

### Expected Behaviour

Expected behaviour is to just display correlations in the data without duplicating them. 

### Data Description

My dataset is the Titanic dataset: https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv

### Code that reproduces the bug

```Python
import pandas as pd

Data = "titanic.csv"
df = pd.read_csv(Data)

from pandas_profiling import ProfileReport

profile = ProfileReport(df.reset_index(drop=True), title="Pandas Profiling Report",)

profile.to_notebook_iframe()
```

### pandas-profiling version

v3.2.0

### Dependencies

```Text
pandas
```

### OS

Windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
@soliverc this is a duplicate request from #824.
There is already a fix, it will be included in the next release of the package: https://github.com/ydataai/pandas-profiling/pull/1000
