### ISSUE TITLE
HTML Profile report keeps crashing browser and jupyter

### ISSUE THREAD

**Issue by snknitin** [ydataai/pandas-profiling#1028]
### Current Behaviour

I reduced the size as much as possible to only do 1000 rows and 118 columns. It still takes 500 seconds to generate a report and crashed the jupyter notebook.  I remember running much larger dataframes quite quickly. So i saved it as a html file.  Now the jupyter notebook tab is fine(as long as i don't open it as a notebook iframe) , but anytime I open the html report it crashes that tab.

Tested it on both  (Mac, Windows) on (Chrome, Vivaldi) browsers. Once as a generated file and once as a downloaded file to avoid any cache issues. The html file crashes on any browser or any device 5 seconds after opening. 

### Expected Behaviour

Report loads for following the data analysis and doesn't crash the browser with an "Aw, Snap ! Something went wrong while displaying the web page" error

### Data Description

Dataset shape is (1000,118) with dtypes: float32(20), int16(44), int64(1), int8(51), object(2)). No missing values 

### pandas-profiling version

v3.2.0

### Dependencies

```Text
pandas==1.3.4
numpy==1.20.3
```

### OS

Windows 11 ,  Mac OS BigSur v11.6.7

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by snknitin** [comment]
UPDATE:

- I have used minimal on the complete data(980k,118) and that runs and generates a report that loads without crashing
- I removed the samples, missing, duplicates etc., by setting them to None
- I ran a correlation report on a larger sample (98k, 118)  and it generated a report just for those which doesn't crash the tab either
- When i run the report only for interactions, even with smaller data (500,118) it crashes the report and tab
- However, when i split the target columns and only provide smaller subset of features but with large data (98k,25) then it runs and loads. 

So essentially the Interactions part was crashing the report html and the way to make it work is to reduce number of features you use for target interaction. I don't think this is a good solution because now we are left with combinations of feature sets we run and multiple reports to view

**Comment by fabclmnt** [comment]
Hi @snknitin,

this is an expectable behavior - the time of computation is expected to increase quadratically with the number of columns available in your dataset, particularly considering correlation matrices and interactions. 

In what concerns your browser crash, it is also a known and expected limitation. It has to do with the amount of information held by the HTML, that for 118 columns is quite a lot, so the only way to depict all the columns is by reducing the amount of information shown.

If this is a blocker for you, I'm happy to discuss more on our commercial offering, otherwise, if no other questions, I'll be closing the issue.
