### ISSUE TITLE
ProfileReport not generated

### ISSUE THREAD

**Issue by Somesh140** [ydataai/pandas-profiling#1031]
### Current Behaviour

 getting KeyError: 'Requested level (var1) does not match index name (None)'

![image](https://user-images.githubusercontent.com/97947690/187729311-e7dd0df9-ed46-44df-be99-4ffe0bb788be.png)
![image](https://user-images.githubusercontent.com/97947690/187729561-0487be2d-27d5-4451-9542-2194ebdcd7c1.png)

### Expected Behaviour

It should generate html file

### Data Description

i am using iris dataset https://github.com/venky14/Machine-Learning-with-Iris-Dataset/raw/master/Iris.csv

### Code that reproduces the bug

```Python
from pandas_profiling import ProfileReport

df2=pd.read_csv(r"https://github.com/venky14/Machine-Learning-with-Iris-Dataset/raw/master/Iris.csv")

profile= ProfileReport(df2)
profile.to_file(output_file='iris.html')
```

### pandas-profiling version

v3.1.0

### Dependencies

```Text
pandas==1.4.2
numpy==1.21.5
```

### OS

Windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
@Somesh140 can you please check wether this behaviour still happens with the latest version of the package?

**Comment by Somesh140** [comment]
@fabclmnt yes it is working fine with the latest version of the package
