### ISSUE TITLE
Getting error while running profile.to_html or profile.to_JSON

### ISSUE THREAD

**Issue by dilkushpatel** [ydataai/pandas-profiling#1097]
getting this error while doing either to_json or to_html

Uncaught SyntaxError: Invalid regular expression: /^[Î‘-ÏŽ]+$/: Range out of order in character class

I'm running code in databricks

code:
import pandas_profiling as pp
import pandas as pd
import json
from datetime import datetime

spark.conf.set("spark.sql.sources.partitionOverwriteMode","dynamic")
spark.conf.set("fs.azure.account.key.synapseadla.dfs.core.windows.net",dbutils.secrets.get(scope = "prod-scope", key = "storage-acc-key"))
#spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")

s_df = spark.read \
  .format("com.databricks.spark.sqldw") \
  .option("url", "jdbc:sqlserver://<sql server>;database=<db>;user=<user>@<server>;password=<password>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.sql.azuresynapse.net;loginTimeout=30;") \
  .option("tempDir", "<temp location>") \
  .option("forwardSparkAzureStorageCredentials", "true") \
  .option("dbTable", "<table name>") \
  .load()

p_df = s_df.toPandas()

profile = pp.ProfileReport(p_df, title="Pandas Profiling Report")

profile.to_html()

**Comment by fabclmnt** [comment]
@dilkushpatel can you provide more details? 

- Python version you are using
- Package version

Also if could provide any detail on the data would be great.

**Comment by dilkushpatel** [comment]
I'm running code in Azure databricks

Python 3.9.5


Name: pandas-profiling
Version: 3.3.0
Summary: Generate profile report for pandas DataFrame
Home-page: https://github.com/ydataai/pandas-profiling
Author: YData Labs Inc
Author-email: opensource@ydata.ai
License: MIT
Location: /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages
Requires: tqdm, requests, matplotlib, scipy, multimethod, pandas, pydantic, htmlmin, missingno, jinja2, joblib, numpy, visions, phik, statsmodels, seaborn, PyYAML, tangled-up-in-unicode
Required-by:

**Comment by sbrugman** [comment]
@dilkushpatel Please provide the full stack trace

**Comment by dilkushpatel** [comment]
@sbrugman  it looks like an issue with pandas or something as any profiling library i use while writing to disk or db i get same error.
I will explore this more on my end and if help needed I will re-open issue.
