### ISSUE TITLE
Updating contributing.md

### ISSUE THREAD

**Issue by prjailani** [ydataai/pandas-profiling#1105]
### Missing functionality

We need to thank the contributors who've contributed to our repository.

### Proposed feature

So, In the end of contributing.md can I add something like "thanks to our contributors" and show their GitHub profiles. If you are ok with this. Please assign me. Thanks.

**Comment by fabclmnt** [comment]
Hi @prjailani that can be found in the [**Acknowledgments** ](section: https://github.com/ydataai/pandas-profiling/blob/master/CONTRIBUTING.md)

Furthermore, for each and every release, we ensure that the contributors are tagged in the changelog. https://pandas-profiling.ydata.ai/docs/master/pages/reference/changelog.html?highlight=release
