### ISSUE TITLE
Bug Report: cannot import name 'Literal' from 'statsmodels.compat.python'

### ISSUE THREAD

**Issue by d0glrq** [ydataai/pandas-profiling#1131]
### Current Behaviour

I get an error when importing `from pandas_profiling import ProfileReport` in jupyter code: `cannot import name 'Literal' from 'statsmodels.compat.python'`

### Expected Behaviour

The import package is successful, no error should be reported

### Data Description

I tried to install pandas-profiling in jupyter, executed `conda install -c conda-forge pandas-profiling`, `conda install -c conda-forge ipywidgets`, `jupyter nbextension enable --py widgetsnbextension`, these were successful of

### Code that reproduces the bug

```Python
---> 54 from pandas_profiling import ProfileReport
     55 
     56 # import findspark

/da2/usr/anaconda3/envs/zycpy37/lib/python3.7/site-packages/pandas_profiling/__init__.py in <module>
      4 """
      5 
----> 6 from pandas_profiling.controller import pandas_decorator
      7 from pandas_profiling.profile_report import ProfileReport
      8 from pandas_profiling.version import __version__

/da2/usr/anaconda3/envs/zycpy37/lib/python3.7/site-packages/pandas_profiling/controller/pandas_decorator.py in <module>
      2 from pandas import DataFrame
      3 
----> 4 from pandas_profiling.profile_report import ProfileReport
      5 
      6 

/da2/usr/anaconda3/envs/zycpy37/lib/python3.7/site-packages/pandas_profiling/profile_report.py in <module>
     14 from pandas_profiling.expectations_report import ExpectationsReport
...
----> 8 from statsmodels.compat.python import lzip, Literal
      9 from statsmodels.compat.scipy import _next_regular
     10 

ImportError: cannot import name 'Literal' from 'statsmodels.compat.python'
```

### pandas-profiling version

3.4.0

### Dependencies

```Text
statsmodels==0.12.2 
pandas==1.3.4
python==3.7.1
Interface:  Jupyter notebook 
 IDE==VS Code
```

### OS

 CentOS Linux release 7.6.1810

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @d0glrq,

we are unable to replicate the issue given the detail you have shared. I'll be closing the issue, but happy to have it re-open in case the problem remains.
