### ISSUE TITLE
Larger correlation plots

### ISSUE THREAD

**Issue by m-a-r-o-u** [ydataai/pandas-profiling#1170]
### Missing functionality

The correlation plot has a lot of information in it
and is currently too small

### Proposed feature

Increase correlation plot size

**Comment by fabclmnt** [comment]
Both the size of the correlation plots and a table version with the cell values were included to mitigate this issue. 

@m-a-r-o-u pandas-profiling==3.6.2 might be worth a try! Thank you for your request!
