### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Filimoa** [ydataai/pandas-profiling#1189]
### Missing functionality

pandas-profiling 3.3.0 requires a version of python <3.11

I'm open to submitting a pull request, what is the underlying issue? 

### Proposed feature

Compatibility with pandas 3.11

**Comment by fabclmnt** [comment]
@Filimoa unfortunatelly for 3.3.0 this is a compatibility that we cannot ensure. 

May I suggest you use more up-to-date versions of pandas-profiling v3.5.0?

**Comment by Filimoa** [comment]
![CleanShot 2022-11-29 at 13 44 19](https://user-images.githubusercontent.com/21352040/204643790-88e291d7-9421-4c56-8a69-3c7f54831621.png)

From what I can tell 3.5.0 isn't compatible with 3.11 either?
