### ISSUE TITLE
Interaction plots for time series data

### ISSUE THREAD

**Issue by MauritsDescamps** [ydataai/pandas-profiling#1223]
### Missing functionality

Interaction plots for numeric time series variables.

### Proposed feature

Calculate interaction plots for both numeric and numeric time series variables. Is there a setting to enable this?

### Alternatives considered

I considered setting ```tsmode=False```, but then I loose the autocorrelation plots.

**Comment by fabclmnt** [comment]
Hi @MauritsDescamps , thank you for your request! 

The solution is expected to be included in the next release.
