### ISSUE TITLE
ModuleNotFoundError: No module named 'ipywidgets'

### ISSUE THREAD

**Issue by zlogz101** [ydataai/pandas-profiling#1224]
### Current Behaviour

**ModuleNotFoundError: No module named 'ipywidgets'**

```bash
>>> import pandas_profiling
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\code\CodeHub\hdt\hdt-tools\sterna\env\lib\site-packages\pandas_profiling\__init__.py", line 6, in <module>
    from pandas_profiling.compare_reports import compare
  File "D:\code\CodeHub\hdt\hdt-tools\sterna\env\lib\site-packages\pandas_profiling\compare_reports.py", line 7, in <module>
    from pandas_profiling.profile_report import ProfileReport
  File "D:\code\CodeHub\hdt\hdt-tools\sterna\env\lib\site-packages\pandas_profiling\profile_report.py", line 9, in <module>
    from ipywidgets.widgets.widget_box import VBox
ModuleNotFoundError: No module named 'ipywidgets'
```

### Expected Behaviour

Import pandas_profiling successfully.

### Data Description

NA.

### Code that reproduces the bug

```Python
import pandas_profiling
```

### pandas-profiling version

v3.6.0

### Dependencies

```Text
astroid==2.12.13
attrs==22.1.0
autopep8==2.0.1
certifi==2022.12.7
charset-normalizer==2.1.1
colorama==0.4.6
contourpy==1.0.6
coverage==7.0.0
cowsay==5.0
cycler==0.11.0
dill==0.3.6
exceptiongroup==1.0.4
fonttools==4.38.0
future==0.18.2
htmlmin==0.1.12
idna==3.4
ImageHash==4.3.1
iniconfig==1.1.1
isort==5.11.2
Jinja2==3.1.2
joblib==1.2.0
kiwisolver==1.4.4
lazy-object-proxy==1.8.0
mando==0.6.4
MarkupSafe==2.1.1
matplotlib==3.6.2
mccabe==0.7.0
multimethod==1.9
networkx==2.8.8
numpy==1.23.5
packaging==22.0
pandas==1.5.2
pandas-profiling==3.6.0
patsy==0.5.3
phik==0.12.3
Pillow==9.3.0
platformdirs==2.6.0
pluggy==1.0.0
pycodestyle==2.10.0
pydantic==1.10.2
pyflakes==3.0.1
pylint==2.15.9
pyparsing==3.0.9
pytest==7.2.0
pytest-mock==3.10.0
python-dateutil==2.8.2
pytoolconfig==1.2.4
pytz==2022.6
PyWavelets==1.4.1
PyYAML==6.0
radon==5.1.0
requests==2.28.1
rope==1.6.0
scipy==1.9.3
seaborn==0.12.1
six==1.16.0
statsmodels==0.13.5
tangled-up-in-unicode==0.2.0
tomli==2.0.1
tomlkit==0.11.6
tqdm==4.64.1
typeguard==2.13.3
typing_extensions==4.4.0
urllib3==1.26.13
visions==0.7.5
wrapt==1.14.1
```

### OS

Windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by zlogz101** [comment]
`pandas_profiling` 3.6 does not add dependency to `ipywidgets`.

It works when install `ipywidgets` manually by `pip3 install`.

**Comment by aquemy** [comment]
Introduced by https://github.com/ydataai/pandas-profiling/commit/4c0b358002d75139c23babc30cbc0c7b23534d92

@fabclmnt we should probably do a hotfix release for this. What do you think?

**Comment by aquemy** [comment]
The problem is that we should not add `ipywidgets` as direct dependency because a lot of people will not want to work with Notebooks. It was removed for this reason: https://github.com/ydataai/pandas-profiling/blob/5e75fd275d14c8ce7ba49d0a15ec26810c4c0e73/docsrc/source/pages/reference/changelog/v2_12_0.rst#%EF%B8%8F-dependencies

**Comment by aquemy** [comment]
This issue was critical enough to trigger a release.

Welcome to [`pandas-profiling` 3.6.1](https://github.com/ydataai/pandas-profiling/releases/tag/v3.6.1)! 

Thank you for reporting this issue!
