### ISSUE TITLE
Report Comparison

### ISSUE THREAD

**Issue by MHUNCHO** [ydataai/pandas-profiling#292]
**Is your feature request related to a problem? Please describe.**
When you're profiling data and have a report later down the line you might have to re-profile that same data to see how the data has progressed. This includes going through both reports and manually comparing the difference in them.

**Describe the solution you'd like**
A nice solution to this would be a system to compare two reports to highlight and outline the differences between the report in terms of how this data is being transformed.

**Comment by djaym7** [comment]
Any update on this feature request ?

**Comment by katewd** [comment]
I would also love to see this feature added. Comparing profiles of the same table at different time points to show data quality improvements is currently a manual process, having a function to automate this would be fantastic. Especially for large databases with many tables. Thanks.

**Comment by sbrugman** [comment]
Agreed, on our roadmap :)

**Comment by fabclmnt** [comment]
We are very happy to announce that this feature is now available in pandas-profiling v3.5.0 🎉
