### ISSUE TITLE
Correlations as a table

### ISSUE THREAD

**Issue by damianbrzoza** [ydataai/pandas-profiling#551]
**Missing functionality**
Heatmap as a description of correlation between variables is a great idea, but in some of my usages I prefer to have numerical values in table form.

**Proposed feature**
Add configuration possibility to show correlation in table form instead of heatmap

I have already coded solution for this issue, take consideration to add this functionality to future release.

**Comment by JianWang2016** [comment]
Could someone please follow-up to include this feature?

**Comment by fabclmnt** [comment]
Supported since version [3.6.0](https://github.com/ydataai/pandas-profiling/releases/tag/v3.6.0)
