### ISSUE TITLE
Provide ways to quickly locate a column in the HTML report

### ISSUE THREAD

**Issue by dclong** [ydataai/pandas-profiling#638]
**Missing functionality**

In the situation of profiling large data frames (hundreds of columns), it is very hard to locate a specific column. It would be great if the HTML report provide a way for this. For example, provide a filtering box. When a user type in something in the filtering box, show only match columns. 

**Proposed feature**

Provide a filtering box in the HTML report. When a user type in something in the filtering box, show only match columns. 

**Alternatives considered**

**Additional context**

**Comment by mohith7548** [comment]
`CTRL + F` is what I'm using currently

**Comment by fabclmnt** [comment]
@g-kabra implemented a great feature to answer this request. 

Since python v3.4.0 variable section filtering is possible.
