### ISSUE TITLE
Feature request: Replace pie chart with alternative

### ISSUE THREAD

**Issue by jamesmyatt** [ydataai/pandas-profiling#679]
**Missing functionality**

Pie charts are horrible. 😝 

**Proposed feature**

Can we have an option to disable the pie chart and/or to replace it with another format, such as a tree map, please?

**Alternatives considered**

 N/A

**Additional context**

Related issues: https://github.com/pandas-profiling/pandas-profiling/issues?q=pie+chart

**Comment by sbrugman** [comment]
@jamesmyatt  Turing off the pie chart is possible by setting the "plot.pie.max_unique" parameter to 0, however this could be documented more clearly (feel free to PR a documentation improvement).

**Comment by fabclmnt** [comment]
Closed by https://github.com/ydataai/pandas-profiling/pull/930
