### ISSUE TITLE
 UserWarning: There was an attempt to calculate the cramers correlation, but this failed.

### ISSUE THREAD

**Issue by NagaKushal8** [ydataai/pandas-profiling#819]
**Describe the bug**
C:\softwares\Anaconda\lib\site-packages\pandas_profiling\model\correlations.py:101: UserWarning: There was an attempt to calculate the cramers correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"cramers": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/pandas-profiling/pandas-profiling/issues
(include the error message: 'No data; `observed` has size 0.')
  warnings.warn(

**To Reproduce**

 

**Version information:**

**Additional context**

**Comment by afeld** [comment]
Duplicate of https://github.com/ydataai/pandas-profiling/issues/811.
