### ISSUE TITLE
High correlation warning printed multiple times

### ISSUE THREAD

**Issue by cdeil** [ydataai/pandas-profiling#824]
I get the same warning "High correlation" with the same other column four times in the report.

Looks like a bug where the warning is accidentally generated multiple times or not de-duplicated properly.

Is it easy to spot the issue or reproduce? Or should I try to extract a standalone test case?

This is with pandas 1.3.0 and pandas-profiling 3.0.0.

<img width="572" alt="Screenshot 2021-09-05 at 18 54 44" src="https://user-images.githubusercontent.com/852409/132135015-45c0a273-763a-430e-b12f-d340e79b3ea7.png">

**Comment by sbrugman** [comment]
The alert is probably generated for each active correlation. This in itself is not wrong, however it should be clear. This can be improved by either merging the alerts or clarifying with respect to which coefficient there is a high correlation.

Feel free to contribute a PR.

**Comment by cdeil** [comment]
What do you mean by "active correlation"?

There are multiple alerts under "alite" saying multiple times `HIGH_CORRELATION` with the same column "belite".
That should be a bug, no?

I tried to have a quick look at the code to see if I can spot how this can happen:
https://github.com/pandas-profiling/pandas-profiling/blob/113277ede126e52717c1ee54014ed8f91fce5d02/src/pandas_profiling/model/alerts.py#L293-L309

Not clear to me what's going on. I can try to debug this and create a test case in the next days.
