### ISSUE TITLE
Report Comparison

### ISSUE THREAD

**Issue by djaym7** [ydataai/pandas-profiling#898]
https://github.com/pandas-profiling/pandas-profiling/issues/292

Is your feature request related to a problem? Please describe.
When you're profiling data and have a report later down the line you might have to re-profile that same data to see how the data has progressed. This includes going through both reports and manually comparing the difference in them.

Describe the solution you'd like
A nice solution to this would be a system to compare two reports to highlight and outline the differences between the report in terms of how this data is being transformed.

**Comment by sbrugman** [comment]
Closing in favour of #292
