### ISSUE TITLE
missing module "utils" 

### ISSUE THREAD

**Issue by Giuppone** [ydataai/pandas-profiling#917]
can not execute examples because unfortunatelly some dependencies are broken (at least in banking and meteorite examples):

**from pandas_profiling.utils.cache import cache_file**

ModuleNotFoundError: No module named 'pandas_profiling.utils'

**Comment by ubabe53** [comment]
Hi Giuppone! 
I have just tried those examples out and I did not have any issues. Initially I was having some problems because I did not set up well the environment, check if it happened the same to you :)

**Comment by sbrugman** [comment]
Closing as this issue could not be reproduced. For future reference, please check [the support page](https://pandas-profiling.ydata.ai/docs/master/rtd/pages/support.html) for help troubleshooting.
