### ISSUE TITLE
Docs are not available (404)

### ISSUE THREAD

**Issue by fbrueck** [ydataai/pandas-profiling#929]
**Describe the bug**

Pandas profiling documentation isn't available.

**To Reproduce**

Open [https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/)

**Comment by rino0601** [comment]
It seems be changed to
https://ydataai.github.io/pandas-profiling/docs/master/rtd/
