### ISSUE TITLE
The running process is not finished

### ISSUE THREAD

**Issue by haloapping** [ydataai/pandas-profiling#937]
I run this example and process is not finished

![image](https://user-images.githubusercontent.com/49802494/156871531-c19cb034-17d6-412e-b426-d802a47c13f1.png)

as well as in other datasets. I use jupyter notebook, windows 10 and python 3.8.12

Any solution about this? I search some solution on internet but not solved

**Comment by mbkupfer** [comment]
This seems like it may be specific to your system. I'm also on windows10/python 3.8.x and do not have such an issue.

Can you try running it as a script (i.e not in jupyter notebook) and seeing if the result is different?

**Comment by fabclmnt** [comment]
Hi @haloapping I'll be closing this issue. But in case you've more details or any other questions I'll be happy to have it re-open.
