### ISSUE TITLE
unable to install pandas-profiling: neither 'setup.py' nor 'pyproject.toml' found

### ISSUE THREAD

**Issue by ellieyuyw** [ydataai/pandas-profiling#943]
I am trying to install pandas profiling on my new Macbook pro M1 (have used pandas profiling on other pcs and it worked amazingly). However, I have tried installing using pip, from git, and from the source, and all requests returned the same output below:

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas_profiling
  Using cached pandas_profiling-3.1.0-py2.py3-none-any.whl (261 kB)
Collecting seaborn>=0.10.1
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting tangled-up-in-unicode==0.1.0
  Using cached tangled_up_in_unicode-0.1.0-py3-none-any.whl (3.1 MB)
Collecting PyYAML>=5.0.0
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in ./Library/Python/3.8/lib/python/site-packages (from pandas_profiling) (1.4.1)
Requirement already satisfied: matplotlib>=3.2.0 in ./Library/Python/3.8/lib/python/site-packages (from pandas_profiling) (3.5.1)
Collecting markupsafe~=2.0.1
  Downloading MarkupSafe-2.0.1-cp38-cp38-macosx_10_9_universal2.whl (18 kB)
Collecting visions[type_image_path]==0.7.4
  Using cached visions-0.7.4-py3-none-any.whl (102 kB)
Collecting pydantic>=1.8.1
  Using cached pydantic-1.9.0-cp38-cp38-macosx_11_0_arm64.whl (2.4 MB)
Collecting requests>=2.24.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting missingno>=0.4.2
  Using cached missingno-0.5.1-py3-none-any.whl (8.7 kB)
Requirement already satisfied: jinja2>=2.11.1 in ./Library/Python/3.8/lib/python/site-packages (from pandas_profiling) (3.0.3)
Requirement already satisfied: numpy>=1.16.0 in ./Library/Python/3.8/lib/python/site-packages (from pandas_profiling) (1.22.3)
Collecting phik>=0.11.1
  Using cached phik-0.12.1.tar.gz (600 kB)
ERROR: phik>=0.11.1 from https://files.pythonhosted.org/packages/02/9c/812ffada4a026ad20ad30318897b46ce3cc46e2eec61a3d9d1cf6699f79a/phik-0.12.1.tar.gz#sha256=63cf160c8950ec46da7a33165deef57f27d29f24b83cf4dd028aa0cb97b73af6 (from pandas_profiling) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Has anyone seen similar errors?

**Comment by bjoseru** [comment]
Same on this new M1 mac: `pip install pandas_profiling` errors out with 
```
❯ pip install pandas-profiling
Collecting pandas-profiling
  Using cached pandas_profiling-3.1.0-py2.py3-none-any.whl (261 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (1.4.1)
Requirement already satisfied: matplotlib>=3.2.0 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (3.5.1)
Requirement already satisfied: seaborn>=0.10.1 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (0.11.2)
Collecting multimethod>=1.4
  Using cached multimethod-1.7-py3-none-any.whl (9.5 kB)
Collecting htmlmin>=0.1.12
  Using cached htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy>=1.4.1 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (1.8.0)
Requirement already satisfied: missingno>=0.4.2 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (0.4.2)
Requirement already satisfied: jinja2>=2.11.1 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (3.0.3)
Requirement already satisfied: numpy>=1.16.0 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (1.22.3)
Collecting tangled-up-in-unicode==0.1.0
  Using cached tangled_up_in_unicode-0.1.0-py3-none-any.whl (3.1 MB)
Requirement already satisfied: requests>=2.24.0 in ./.venv-3.10.3-eda/lib/python3.10/site-packages (from pandas-profiling) (2.27.1)
Collecting PyYAML>=5.0.0
  Using cached PyYAML-6.0-cp310-cp310-macosx_11_0_arm64.whl (173 kB)
Collecting visions[type_image_path]==0.7.4
  Using cached visions-0.7.4-py3-none-any.whl (102 kB)
Collecting phik>=0.11.1
  Using cached phik-0.12.1.tar.gz (600 kB)
ERROR: phik>=0.11.1 from https://files.pythonhosted.org/packages/02/9c/812ffada4a026ad20ad30318897b46ce3cc46e2eec61a3d9d1cf6699f79a/phik-0.12.1.tar.gz#sha256=63cf160c8950ec46da7a33165deef57f27d29f24b83cf4dd028aa0cb97b73af6 (from pandas-profiling) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

Any help appreciated.

**Comment by Wh1isper** [comment]
same problem on arm

its phik problem, install phik==0.11.1 before install pandas-profiling would help

**Comment by RUrlus** [comment]
@ellieyuyw There was an issue with the source distribution missing required files. KaveIO/PhiK#49 fixes the issue and adds wheels for ARM MacOS.

**Comment by bjoseru** [comment]
@RUrlus  @ellieyuyw @Wh1isper

confirming `pandas-profiling-3.1.0` is installing now successfully using `phik-0.12.2-cp310-cp310-macosx_11_0_arm64.whl`

thanks everyone for the quick fix

**Comment by ellieyuyw** [comment]
problem solved! Thanks everybody :)
