### ISSUE TITLE
pandas-profiling giving random error

### ISSUE THREAD

**Issue by kameshkotwani** [ydataai/pandas-profiling#949]
**Describe the bug**
when putting a data-frame inside the ProfileReport class I am getting random errors on different runs.

**To Reproduce**
Create a data frame from ```seaborn.load_dataset('titanic')``` and try creating a profile report.
```python
import pandas as pd
import seaborn as sns
from pandas_profiling import ProfileReport
titanic = sns.load_dataset('titanic')
profile = ProfileReport(titanic,title="titanic dataset")
try:
  profile.to_file('output.html`')
except Exception as e:
  print(e)
```

 

**Version information:**
pandas-profiling: 3.1.0

**Additional context**
Video has been posted

https://user-images.githubusercontent.com/36355951/161377743-684efb25-6be9-42c2-8667-4b881cd08bc5.mp4

**Comment by aronvandepol** [comment]
Seems to be the same issue described in #911 - fix is also there.

**Comment by sbrugman** [comment]
Resolved in https://github.com/ydataai/pandas-profiling/pull/945
