### ISSUE TITLE
latest version 3.2.0 is broken in google colab

### ISSUE THREAD

**Issue by athulkrishna2015** [ydataai/pandas-profiling#966]
**Describe the bug**

**To Reproduce**
profile = ProfileReport(df, title="Pandas Profiling Report")
profile.to_notebook_iframe()
 will throw error
<!--

anyone want a dirty fix 
!pip install pandas-profiling==3.1.0 
instead

**Comment by athulkrishna2015** [comment]
!pip install pandas-profiling==3.1.0
dirty fix

**Comment by sbrugman** [comment]
Will look into this

**Comment by sbrugman** [comment]
@athulkrishna2015 thanks for reporting. The versions of "markupsafe" and "jinja2" are incompatible on colab.

Solution:
`!pip install -U "jinja2>=2.3"`

Will update the dependencies accordingly.
